version: "3.8"
services:
  sql:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=db_user
      - MYSQL_DATABASE=db
      - MYSQL_PASSWORD=pwd
  auth:
    build: ./auth-service
    tty: true
    ports:
        - '30500:80'
    environment:
        - DB_LOCATION=sql
        - DB_USER=db_user
        - DB_PASSWORD=pwd
        - DB_NAME=db  
  product:
    build: ./products-service
    tty: true
    ports:
        - '30501:80'  
    environment:
        - DB_LOCATION=sql
        - DB_USER=db_user
        - DB_PASSWORD=pwd
        - DB_NAME=db
        - AUTH_URL=http://auth
